### PR TITLE
WIP: Bug 1969960: credentials are not automatically updated

### PR DESCRIPTION
**Pull request by janosdebugs**
This change adds the [k8s oVirt credentials monitor](https://github.com/oVirt/k8sOVirtCredentialsMonitor), which automatically updates oVirt credentials when a secret is changed. The change is backward compatible and should be deployable with the operator without changes.

⚠️ This change depends on oVirt/k8sOVirtCredentialsMonitor#23 which needs to be merged before this change can proceed.

### CODE REVIEW

**Comment by jsafrane** [comment]
I am not a big fan of CSI drivers talking to Kubernetes API server at all. CSI is container-orchestrator agnostic, a driver should be able to run e.g. in Nomad.

It is trivial to update the CSI driver operator to restart the CSI driver pods when a Secrets with credentials change or when a ConfigMap with the driver config changes. Would it work for you better?

**Comment by jsafrane** [comment]
Another "popular" choice are Secrets / ConfigMap volumes - content of a Secerets/ConfigMap object is visible in a container as a file. When Secrets object in Kubernetes is updated, content of the file is updated too (via some atomic rename magic). You can either read the file every time before talking to the oVirt API or have inotify on it to get an event when it changes.

**Comment by janosdebugs** [comment]
Closing as per discussion, we'll switch to restarting from the operator.

**Pull request closed without merging**
